[paths]
i3config = "/home/ggljzr/.i3/config"
xresources = "/home/ggljzr/.Xresources"
i3blocks = "/home/ggljzr/.i3blocks.conf"
compton = "/home/ggljzr/.config/compton.conf"
userchrome = "/home/ggljzr/.mozilla/firefox/so3i8lhu.default/chrome/userChrome.css"
