name = "Dosbox 2"

[colors]
black = "#000000"
darkGrey = "#555555"

darkRed = "#CD0000"
red = "#FF0000"

darkGreen = "#00CD00"
green = "#00FF00"

darkYellow = "#CDCD00"
yellow = "#FFFF00"

darkBlue = "#4682B4"
blue = "#1E90FF"

darkMagenta = "#CD00CD"
magenta = "#FF00FF"

darkCyan = "#00CDCD"
cyan = "#00FFFF"

lightGrey = "#999999"
white = "#ffffff"

background = "#000000"
foreground = "#ffffff"

[i3]

border = 1
gaps-inner = 16
gaps-outer = 0
    
    [i3.windows]
    focused = "white"
    inactive = "lightGrey"
    unfocused = "lightGrey"
    urgent = "red"
    foreground = "black"

[firefox]
toolbar = "black"
urlbar = "#285577"
foreground = "white"
background = "darkGrey"
tabselect = "#285577"

[wallpaper]
    pic = "/home/ggljzr/Pictures/black.png"

[other]
font = "Terminus"
font-size = 10
shadows = "none" #mild, thick or none
