name = "Dosbox"

[colors]
black = "#000000"
darkGrey = "#555555"

darkRed = "#CD0000"
red = "#FF0000"

darkGreen = "#00CD00"
green = "#00FF00"

darkYellow = "#CDCD00"
yellow = "#FFFF00"

darkBlue = "#000099"
blue = "#526FFF"

darkMagenta = "#CD00CD"
magenta = "#FF00FF"

darkCyan = "#00CDCD"
cyan = "#00FFFF"

lightGrey = "#999999"
white = "#ffffff"

background = "#000000"
foreground = "#ffffff"

[i3]
    [i3.windows]
    focused = "#285577"
    inactive = "#222222"
    unfocused = "#222222"
    urgent = "#222222"
    foreground = "white"
    wborder = "#333333"
    
[wallpaper]
    pic = "/home/kali/Pictures/000.jpg"

[other]
shadows = "none" #mild, thick or none
