name = "Dosbox 2"

[colors]
black = "#000000"
darkGrey = "#555555"

darkRed = "#CD0000"
red = "#FF0000"

darkGreen = "#00CD00"
green = "#00FF00"

darkYellow = "#CDCD00"
yellow = "#FFFF00"

darkBlue = "#0000dd"
blue = "#1E90FF"

darkMagenta = "#CD00CD"
magenta = "#FF00FF"

darkCyan = "#00CDCD"
cyan = "#00FFFF"

lightGrey = "#999999"
white = "#ffffff"

background = "#000000"
foreground = "#ffffff"

[i3]

border = 3
    
    [i3.windows]
    focused = "darkBlue"
    inactive = "darkGrey"
    unfocused = "darkGrey"
    urgent = "red"
    foreground = "white"

[firefox]
toolbar = "black"
urlbar = "#285577"
foreground = "white"
background = "darkGrey"
tabselect = "#285577"

[other]
font = "Terminus"
font-size = 10
shadows = "none" #mild, thick or none
