#http://terminal.sexy/#EBAQubm5EBAQfHx8jo6OoKCgaGhodHR0hoaGubm5UlJSfHx8jo6OoKCgaGhodHR0hoaG9_f3
name = "grayscale"

[colors]
black = "#101010"
darkGrey = "#525252"

darkRed = "#7c7c7c"
red = "#7c7c7c"

darkGreen = "#8e8e8e"
green = "#8e8e8e"

darkYellow = "#a0a0a0"
yellow = "#a0a0a0"

darkBlue = "#686868"
blue = "#686868"

darkMagenta = "#747474"
magenta = "#747474"

darkCyan = "#868686"
cyan = "#868686"

lightGrey = "#b9b9b9"
white = "#f7f7f7"

background = "#101010"
foreground = "#f7f7f7"

[i3]

border = 0
gaps-inner = 0
gaps-outer = 0
    
[wallpaper]
    pic = "/home/ggljzr/Pictures/black.png"

[other]
font = "Terminus"
font-size = 10
shadows = "none" #mild, thick or none
