name = "gray"

[colors]
black = "#3c3c3b"
darkGrey = "#545454"

darkRed = "#834d4b"
red = "#9f5e5b"

darkGreen = "#4b8365"
green = "#579876"

darkYellow = "#83694b"
yellow = "#9f7f5B"

darkBlue = "#4b6983"
blue = "#6084a4"

darkMagenta = "#834B7E"
magenta = "#A25D9C"

darkCyan = "#4B8380"
cyan = "#5b9f9c"

lightGrey = "#dddddd"
white = "#f0f0f0"

background = "#dddddd"
foreground = "#3c3c3b"


#this can be ommitted
#then it defaults to
#border = 0
#gaps-inner, gaps-outer = 0
[i3]

border = 4
gaps-inner = 16
gaps-outer = 0
    
    #this can also be ommitted
    #or only some options can be ommitted
    [i3.windows]
    focused = "black"
    inactive = "lightGrey"
    unfocused = "lightGrey"
    urgent = "darkRed"
    foreground = "white"

[firefox]
    foreground = "white"

[wallpaper]
    pic = "/home/ggljzr/Pictures/win95.png"
    mode = "scale" #feh bg mode (scale, tile, center). defaults to scale

[other]
font = "Terminus"
font-size = 10
shadows = "none" #mild, thick or none
