#https://github.com/roosta/vim-srcery
name = "Srcery"

[colors]
black = "#1C1819"
darkGrey = "#2D2C29"

darkRed = "#FF3128"
red = "#F75341"

darkGreen = "#519F50"
green = "#98BC37"

darkYellow = "#FBB829"
yellow = "#FED06E"

darkBlue = "#5573A3"
blue = "#8EB2F7"

darkMagenta = "#E02C6D"
magenta = "#E35682"

darkCyan = "#0AAEB3"
cyan = "#53FDE9"

lightGrey = "#918175"
white = "#FCE8C3"

background = "#1C1819"
foreground = "#FCE8C3"


#this can be ommitted
#then it defaults to
#border = 0
#gaps-inner, gaps-outer = 0
[i3]

border = 0
gaps-inner = 0
gaps-outer = 0
    
    #this can also be ommitted
    #or only some options can be ommitted
    [i3.windows]
    focused = "darkGreen"
    inactive = "darkGrey"
    unfocused = "darkGrey"
    urgent = "darkRed"
    foreground = "white"

#firefox options can also be ommited
#[firefox]
#foreground = "#005500"
#background = "white"
#urlbar = "darkRed"
#toolbar = "#ff0000"
#tabselect = "#00ff88"

[wallpaper]
    pic = "/home/ggljzr/Pictures/bird.jpg"
    mode = 'tile' #options for feh --bg-, defaults to scale if ommitted

[other]
font = "Terminus"
font-size = 10
shadows = "none" #mild, thick or none
